version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: lab_access_db
    environment:
      POSTGRES_USER: mrlhou
      POSTGRES_PASSWORD: mrlhou2001
      POSTGRES_DB: lab_access
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrlhou"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
